#!/bin/bash

echo "🚀 GitHub Push Helper for aichatbotsolutions"
echo "============================================"
echo ""
echo "Your changes are committed locally and ready to push!"
echo ""
echo "📋 STEP 1: Create a Personal Access Token"
echo "   1. Open this link: https://github.com/settings/tokens/new"
echo "   2. Token name: 'aichatbotsolutions-push'"
echo "   3. Expiration: 30 days (or your preference)"
echo "   4. Select scopes: ✓ repo (all checkboxes under repo)"
echo "   5. Click 'Generate token' at the bottom"
echo "   6. COPY THE TOKEN (starts with ghp_)"
echo ""
echo "📋 STEP 2: Push your code"
echo "   Run this command:"
echo "   git push -u origin main"
echo ""
echo "   When prompted:"
echo "   Username: theburgerllc"
echo "   Password: [PASTE YOUR TOKEN HERE]"
echo ""
echo "🎯 Alternative: Set token permanently (optional)"
echo "   git remote set-url origin https://theburgerllc:YOUR_TOKEN@github.com/theburgerllc/aichatbotsolutions.git"
echo ""
read -p "Press Enter to continue..."
